sudo: required
language: generic

services:
  - docker

before_install:
  - docker build -t lukaszmikol/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true lukaszmikol/docker-react npm run test
