language: node_js
sudo: required

services:
  - docker

before_install:
  - docker build -t lukaszmikol/docker-react -f Dockerfile.dev . 

script:
  - docker run lukaszmikol/docker-react nprm run test -- --coverage
  